INSERT INTO reference_values (vocabulary, value, label) VALUES
  ('signal_types', 'mic', 'Mic'),
  ('signal_types', 'line', 'Line'),
  ('signal_types', 'di', 'DI'),
  ('signal_types', 'return', 'Return'),
  ('signal_types', 'aux', 'Aux'),
  ('preamp_connectors', 'xlr', 'XLR'),
  ('preamp_connectors', 'jack_ts', 'Jack TS'),
  ('preamp_connectors', 'jack_trs', 'Jack TRS'),
  ('preamp_connectors', 'rca', 'RCA'),
  ('preamp_connectors', 'combo', 'Combo'),
  ('preamp_connectors', 'usb', 'USB'),
  ('signal_cable_types', 'xlr', 'XLR'),
  ('signal_cable_types', 'jack_ts', 'Jack TS'),
  ('signal_cable_types', 'jack_trs', 'Jack TRS'),
  ('signal_cable_types', 'rca', 'RCA'),
  ('signal_cable_types', 'combo', 'Combo'),
  ('speaker_cable_types', 'xlr', 'XLR'),
  ('speaker_cable_types', 'nl4', 'NL4 (Speakon)'),
  ('speaker_cable_types', 'nl8', 'NL8 (Speakon)'),
  ('speaker_cable_types', 'jack_ts', 'Jack TS'),
  ('output_types', 'foh', 'FOH'),
  ('output_types', 'monitor', 'Monitor'),
  ('output_types', 'sub', 'Sub'),
  ('output_types', 'aux', 'Aux'),
  ('output_types', 'matrix', 'Matrix'),
  ('output_types', 'stereo', 'Stereo'),
  ('output_types', 'iem', 'IEM'),
  ('mic_stands', 'straight', 'Straight'),
  ('mic_stands', 'boom', 'Boom'),
  ('mic_stands', 'low', 'Low'),
  ('mic_stands', 'desk', 'Desk'),
  ('mic_stands', 'clip', 'Clip'),
  ('mic_stands', 'none', 'None'),
  ('power_connectors', 'schuko', 'Schuko'),
  ('power_connectors', 'cee16', 'CEE 16A (1-fas)'),
  ('power_connectors', 'cee32', 'CEE 32A (1-fas)'),
  ('power_connectors', 'cee16_3ph', 'CEE 16A (3-fas)'),
  ('power_connectors', 'cee32_3ph', 'CEE 32A (3-fas)'),
  ('power_connectors', 'powercon', 'PowerCon'),
  ('power_connectors', 'powercon_true1', 'PowerCon TRUE1'),
  ('power_connectors', 'iec', 'IEC C13'),
  ('truss_types', 'box', 'Box'),
  ('truss_types', 'ladder', 'Ladder'),
  ('truss_types', 'circle', 'Circle'),
  ('truss_types', 'straight', 'Straight'),
  ('truss_types', 'none', 'None')
